### ISSUE TITLE
No hosts matched

### ISSUE THREAD

**Issue by CE93Geek** [sergevs/ansible-os-autoinstall#1]
Hi, I'm trying to use this project to automate the installation of redhat workstation 7.4. I have configured the pxe boot infrastructure (tftp, http, dhcp), and made a kickstart file for redhat workstation 7.4 which I have tested it separately and it works. Now when I try to run site.yml file it gives me an error "no host matched". I'm a bit confused about your hosts file configuration because what I know is that the inventory file should contain the IP or the hostname of the targeted machine, but I don't get the way your file is configured, I appreciate a little explanation about it. Thanx!

**Comment by sergevs** [comment]
> I'm a bit confused about your hosts file configuration because what I know is that the inventory file should contain the IP or the hostname of the targeted machine

That's correct. The [boot] group should contain the host where kickstart files deployed.
The rest sections is the groups of hosts by distribution type and the hosts is not supposed to be exists at the time the playbook running - but used to create kickstart files with given attributes.

please provide your inventory(hosts) file - and I'll help you with the error you get

**Comment by sergevs** [comment]
> Error "no host matched"
Seems you had an incorrect inventory configuration as this is error actually raised by ansible.
