### ISSUE TITLE
example to setup required services should be made with ansible

### ISSUE THREAD

**Issue by gthieleb** [sergevs/ansible-os-autoinstall#3]
The example configuration for the required boot services should be done with ansible. This should be the prefered way to setup a remote "boot" server.

**Comment by sergevs** [comment]
Please read "Caveats" section in documentation. The example configuration is provided as an example only and can't be a preferred  way. I never use it in real production environments where dhcp is usually served by a network device and kickstart and distribution files served by a special infrastructure service which is not nginx. More over the example setup is applicable to centos 7 only, while the network boot environment can be setup on any Unix distribution or even on a network device which provides the required capabilities.
